### ISSUE TITLE
Step 3: Setting up IAM permissions, CloudFormation parameters

### ISSUE THREAD

**Issue by tituschu0628** [kubecost/cloudformation#12]
Hi,

I am a bit confused at Step 3 in this page [https://guide.kubecost.com/hc/en-us/articles/4407595928087-AWS-Cloud-Integration](https://guide.kubecost.com/hc/en-us/articles/4407595928087-AWS-Cloud-Integration)

i'm at
My kubernetes clusters all run in the same account as the master payer account.
Download this file: https://raw.githubusercontent.com/kubecost/cloudformation/master/kubecost-single-account-permissions.yaml
...

the webpage says
```
Set the following parameters:

AthenaCURBucket: The bucket where the CUR is sent from the “Setting up the CUR” step
SpotDataFeedBucketName: Optional. The bucket where the spot data feed is sent from the “Setting up the Spot Data feed” step (see below)
```

while the actual yaml is
```
Parameters:
  AthenaCURBucket:
    Description: The bucket that athena results are written to
    Type: String
  SpotDataFeedBucketName:
    Description: Optional. The AWS account ID containing the cluster with kubecost.
    Type: String
```

so which bucket do i specify for `AthenaCURBucket`?
the one from Step 1: Setting up the CUR 
or one from Step 2: Setting up Athena (`aws-athena-query-results-*`)
